INSERT INTO MENU VALUES(
'M01','298_2BlF7sqUMnEo8W7XLQ')
INSERT INTO MENU VALUES(
'M02','qJJIvbYPOBIuyaTXdh1aOA')
INSERT INTO MENU VALUES(
'M03','tRhgp6syOtfBJ6MVWfw_kw')
INSERT INTO MENU VALUES(
'M04','qa3NxPFkedBH0UQw-K22eA')

INSERT INTO CUSTOMER VALUES(
'CoEb1P8GdB72yjbT6cJuBQ','S','Meg','F','Chicago','IL')
INSERT INTO CUSTOMER VALUES(
'B-AyQDD2yc_jcNmPLjaOZQ','E','Jeannine','F','Silver Spring','MD')
INSERT INTO CUSTOMER VALUES(
'FRa_eFg0qSnRxAH2HegdyA','B','Miss','F','Hyattsville','MD')
INSERT INTO CUSTOMER VALUES(
'tsN4RLhkX7ytyW-w4IMzBg','L','Mia','F','Elkridge','MD')
INSERT INTO CUSTOMER VALUES(
'3VQYOO7nX6owW7ZAKpRC0g','B','James','M','Providence','RI')